version: "3"
services:
  web:
    build: .
    ports:
      - "8888:8888"
    environment:
      - SERVER_PORT=8888
      - MONGODB_URI=mongodb://db:27017/annotator
    links:
      - db
      - vep
    depends_on:
      - db

  db:
    build: https://github.com/genome-nexus/genome-nexus-importer.git
    environment:
      - REF_ENSEMBL_VERSION=${REF_ENSEMBL_VERSION}
    restart: always

  vep:
    image: genomenexus/gn-vep:27223ebc69be55f8d6b31b9111c697ff7b2c0850
    environment:
      - SERVER_PORT=6060
      - VEP_ASSEMBLY=${VEP_ASSEMBLY}
    restart: always
    ports:
      - "6060:6060"
    volumes:
      - ${VEP_CACHE}:/opt/vep/.vep/:ro
