apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: gn-spring-boot
  name: gn-spring-boot
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/gn-spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gn-spring-boot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: gn-spring-boot
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "8888"
        - name: MONGODB_URI
          value: mongodb://gn-mongo-mongodb:27017/annotator
        image: genomenexus/gn-spring-boot:v1.0.0-36-gb677139
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /#/home
            port: 8888
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 5
        name: gn-spring-boot
        ports:
        - containerPort: 8888
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
